### ISSUE TITLE
Error Virgl

### ISSUE THREAD

**Issue by Kokinyo** [KreitinnSoftware/MiceWine#2]
glTexImage2D returned glError 0x501

**Comment by KreitinnSoftware** [comment]
What your device? What games you trying to play? Send the entire log

**Comment by Kokinyo** [comment]
Honor 20lite cpu kirin710f 4gbram Mali-G51 games dmc4 demo, marvel lego superhero
[micewine.log](https://github.com/KreitinnSoftware/MiceWine/files/13626082/micewine.log)

**Comment by Kokinyo** [comment]
![Screenshot_20231210_013055_com termux x11](https://github.com/KreitinnSoftware/MiceWine/assets/82234530/2643c9b7-866b-4379-a01a-c82c5d073046)

**Comment by Kokinyo** [comment]
![Uploading Screenshot_20231210_020654_com.termux.x11.jpg…]()

**Comment by Kokinyo** [comment]
![Screenshot_20231210_020654_com termux x11](https://github.com/KreitinnSoftware/MiceWine/assets/82234530/a4013c4f-09be-4d91-ae4b-f24cfd2b0e07)
