### ISSUE TITLE
Wine does not load

### ISSUE THREAD

**Issue by philpsdf** [KreitinnSoftware/MiceWine#3]
Samsung S24 Ultra 
Termux-x11 opens without Wine loaded.

**Comment by ACASADOEMULADOR** [comment]
reiniciar o aparelho ajuda

**Comment by philpsdf** [comment]
> reiniciar o aparelho ajuda

Para mim não funcionou

**Comment by ACASADOEMULADOR** [comment]
tenta atualizar o box dele baixa o box64 android e abre o zip d micewine com winrar e joga a box64 dentro da pasta bin e instala e tenta outra coisa baixe tudo atualizado no github termux e termux x11 olhe no x11 quando o prefixo estiver sendo criado as vezes ele pede pra clicar no wine modo download qual e seu processador e qual a versa odo mice voce esta tentando instalar

**Comment by philpsdf** [comment]
Consegui fazer o wine subir instalando o box64droid depois do micewine.
Agora o que não abre é a Steam.

**Comment by ACASADOEMULADOR** [comment]
EXITE INUMERAS COISAS QUE SE TEM QUE RESOLVER PARA FUNCIONAR A VERSAO QUE VOCE BAIXOU JA ESTA OBSOLETA
